Feature/issue#139 Actualización de Estilos
udistrital/sga_cliente_gestion_periodo_mf pull request #10
Opened 2024-04-15 03:50 UTC by redflox

## Actualización de Estilos

- **Eliminación de Bootstrap:** Se removió completamente Bootstrap del proyecto.
- **Reestilización:** Se eliminaron todos los estilos preexistentes.
- **Implementación de Angular Material:** Se utilizó Angular Material para la reestilización del proyecto.
- **Estilos para Formularios:** Se aplicaron nuevos estilos específicos para formularios.
- **Estilos Generales:** Se añadieron estilos generales para las tarjetas de información, los cuales se incluyeron en el core del proyecto.
---
udistrital/sga_documentacion#139

2024-04-16 14:51 UTC, NeFaWaltPint requested changes
Requiere ajustar el path de _periodos_ a **periodo**, demás ok.

2024-04-16 14:51 UTC, NeFaWaltPint commented on src/app/app-routing.module.ts
> +  providers: [{ provide: APP_BASE_HREF, useValue: "/periodos/" }],
```suggestion
  providers: [{ provide: APP_BASE_HREF, useValue: "/periodo/" }],
```
aquí creo se debe **periodo** ya que la url del menú está así actualmente: 
`https://pruebassgamicroclientes.portaloas.udistrital.edu.co/periodo/list-periodo`

2024-04-16 14:51 UTC, NeFaWaltPint commented on src/app/app.config.ts
> +    { provide: APP_BASE_HREF, useValue: '/periodos/' },
```suggestion
    { provide: APP_BASE_HREF, useValue: '/periodo/' },
```

2024-04-16 14:54 UTC, NeFaWaltPint approved these changes

2024-04-16 14:54 UTC, NeFaWaltPint commented
Resuelvo el microajuste para agilizar.

2024-05-07 15:46 UTC, fabianbarreto02 approved these changes

2024-05-07 15:47 UTC, merged